server:
  port: 8080

spring:
  application:
    name: members
  datasource:
    url: jdbc:h2:mem:starterdb
    password:
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
      #hibernate:
    #ddl-auto: update

